
import { CountryMapping } from './types';

export const COUNTRIES: CountryMapping[] = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', languages: [{ name: 'Pashto', code: 'ps' }, { name: 'Dari', code: 'prs' }] },
  { name: 'Albania', code: 'AL', flag: '🇦🇱', languages: [{ name: 'Albanian', code: 'sq' }] },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', languages: [{ name: 'Arabic', code: 'ar' }, { name: 'Berber', code: 'ber' }] },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩', languages: [{ name: 'Catalan', code: 'ca' }] },
  { name: 'Angola', code: 'AO', flag: '🇦🇴', languages: [{ name: 'Portuguese', code: 'pt' }] },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲', languages: [{ name: 'Armenian', code: 'hy' }] },
  { name: 'Australia', code: 'AU', flag: '🇦🇺', languages: [{ name: 'English', code: 'en' }] },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', languages: [{ name: 'German', code: 'de' }] },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', languages: [{ name: 'Azerbaijani', code: 'az' }] },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸', languages: [{ name: 'English', code: 'en' }] },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', languages: [{ name: 'Bengali', code: 'bn' }] },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾', languages: [{ name: 'Belarusian', code: 'be' }, { name: 'Russian', code: 'ru' }] },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', languages: [{ name: 'Dutch', code: 'nl' }, { name: 'French', code: 'fr' }, { name: 'German', code: 'de' }] },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿', languages: [{ name: 'English', code: 'en' }] },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯', languages: [{ name: 'French', code: 'fr' }] },
  { name: 'Bolivia', code: 'BO', flag: '🇧🇴', languages: [{ name: 'Spanish', code: 'es' }, { name: 'Quechua', code: 'qu' }] },
  { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', languages: [{ name: 'Bosnian', code: 'bs' }] },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼', languages: [{ name: 'English', code: 'en' }, { name: 'Tswana', code: 'tn' }] },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', languages: [{ name: 'Portuguese', code: 'pt' }] },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', languages: [{ name: 'Bulgarian', code: 'bg' }] },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭', languages: [{ name: 'Khmer', code: 'km' }] },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲', languages: [{ name: 'French', code: 'fr' }, { name: 'English', code: 'en' }] },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', languages: [{ name: 'English', code: 'en' }, { name: 'French', code: 'fr' }] },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'China', code: 'CN', flag: '🇨🇳', languages: [{ name: 'Chinese (Simplified)', code: 'zh-CN' }] },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', languages: [{ name: 'Croatian', code: 'hr' }] },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', languages: [{ name: 'Greek', code: 'el' }, { name: 'Turkish', code: 'tr' }] },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿', languages: [{ name: 'Czech', code: 'cs' }] },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', languages: [{ name: 'Danish', code: 'da' }] },
  { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Estonia', code: 'EE', flag: '🇪🇪', languages: [{ name: 'Estonian', code: 'et' }] },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', languages: [{ name: 'Amharic', code: 'am' }] },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯', languages: [{ name: 'English', code: 'en' }, { name: 'Fijian', code: 'fj' }] },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', languages: [{ name: 'Finnish', code: 'fi' }, { name: 'Swedish', code: 'sv' }] },
  { name: 'France', code: 'FR', flag: '🇫🇷', languages: [{ name: 'French', code: 'fr' }] },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪', languages: [{ name: 'Georgian', code: 'ka' }] },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', languages: [{ name: 'German', code: 'de' }] },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', languages: [{ name: 'English', code: 'en' }] },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', languages: [{ name: 'Greek', code: 'el' }] },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹', languages: [{ name: 'French', code: 'fr' }, { name: 'Haitian Creole', code: 'ht' }] },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', languages: [{ name: 'Hungarian', code: 'hu' }] },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', languages: [{ name: 'Icelandic', code: 'is' }] },
  { name: 'India', code: 'IN', flag: '🇮🇳', languages: [{ name: 'Hindi', code: 'hi' }, { name: 'English', code: 'en' }, { name: 'Bengali', code: 'bn' }] },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', languages: [{ name: 'Indonesian', code: 'id' }] },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', languages: [{ name: 'Persian', code: 'fa' }] },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', languages: [{ name: 'Arabic', code: 'ar' }, { name: 'Kurdish', code: 'ku' }] },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', languages: [{ name: 'English', code: 'en' }, { name: 'Irish', code: 'ga' }] },
  { name: 'Israel', code: 'IL', flag: '🇮🇱', languages: [{ name: 'Hebrew', code: 'he' }, { name: 'Arabic', code: 'ar' }] },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', languages: [{ name: 'Italian', code: 'it' }] },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲', languages: [{ name: 'English', code: 'en' }] },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', languages: [{ name: 'Japanese', code: 'ja' }] },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', languages: [{ name: 'Kazakh', code: 'kk' }, { name: 'Russian', code: 'ru' }] },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', languages: [{ name: 'Swahili', code: 'sw' }, { name: 'English', code: 'en' }] },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', languages: [{ name: 'Kyrgyz', code: 'ky' }, { name: 'Russian', code: 'ru' }] },
  { name: 'Laos', code: 'LA', flag: '🇱🇦', languages: [{ name: 'Lao', code: 'lo' }] },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻', languages: [{ name: 'Latvian', code: 'lv' }] },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', languages: [{ name: 'Arabic', code: 'ar' }, { name: 'French', code: 'fr' }] },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹', languages: [{ name: 'Lithuanian', code: 'lt' }] },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', languages: [{ name: 'Luxembourgish', code: 'lb' }, { name: 'French', code: 'fr' }, { name: 'German', code: 'de' }] },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬', languages: [{ name: 'Malagasy', code: 'mg' }, { name: 'French', code: 'fr' }] },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', languages: [{ name: 'Malay', code: 'ms' }] },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', languages: [{ name: 'Dhivehi', code: 'dv' }] },
  { name: 'Mali', code: 'ML', flag: '🇲🇱', languages: [{ name: 'French', code: 'fr' }] },
  { name: 'Malta', code: 'MT', flag: '🇲🇹', languages: [{ name: 'Maltese', code: 'mt' }, { name: 'English', code: 'en' }] },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Moldova', code: 'MD', flag: '🇲🇩', languages: [{ name: 'Romanian', code: 'ro' }] },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨', languages: [{ name: 'French', code: 'fr' }] },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳', languages: [{ name: 'Mongolian', code: 'mn' }] },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪', languages: [{ name: 'Montenegrin', code: 'sr' }] },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', languages: [{ name: 'Arabic', code: 'ar' }, { name: 'Berber', code: 'ber' }] },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲', languages: [{ name: 'Burmese', code: 'my' }] },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵', languages: [{ name: 'Nepali', code: 'ne' }] },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱', languages: [{ name: 'Dutch', code: 'nl' }] },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', languages: [{ name: 'English', code: 'en' }, { name: 'Maori', code: 'mi' }] },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', languages: [{ name: 'English', code: 'en' }, { name: 'Hausa', code: 'ha' }, { name: 'Yoruba', code: 'yo' }, { name: 'Igbo', code: 'ig' }] },
  { name: 'North Korea', code: 'KP', flag: '🇰🇵', languages: [{ name: 'Korean', code: 'ko' }] },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', languages: [{ name: 'Norwegian', code: 'no' }] },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', languages: [{ name: 'Urdu', code: 'ur' }, { name: 'English', code: 'en' }] },
  { name: 'Palestine', code: 'PS', flag: '🇵🇸', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾', languages: [{ name: 'Spanish', code: 'es' }, { name: 'Guarani', code: 'gn' }] },
  { name: 'Peru', code: 'PE', flag: '🇵🇪', languages: [{ name: 'Spanish', code: 'es' }, { name: 'Quechua', code: 'qu' }, { name: 'Aymara', code: 'ay' }] },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', languages: [{ name: 'Filipino', code: 'fil' }, { name: 'English', code: 'en' }] },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', languages: [{ name: 'Polish', code: 'pl' }] },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', languages: [{ name: 'Portuguese', code: 'pt' }] },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', languages: [{ name: 'Romanian', code: 'ro' }] },
  { name: 'Russia', code: 'RU', flag: '🇷🇺', languages: [{ name: 'Russian', code: 'ru' }] },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳', languages: [{ name: 'French', code: 'fr' }, { name: 'Wolof', code: 'wo' }] },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', languages: [{ name: 'Serbian', code: 'sr' }] },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', languages: [{ name: 'English', code: 'en' }, { name: 'Malay', code: 'ms' }, { name: 'Chinese', code: 'zh' }, { name: 'Tamil', code: 'ta' }] },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰', languages: [{ name: 'Slovak', code: 'sk' }] },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮', languages: [{ name: 'Slovenian', code: 'sl' }] },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', languages: [{ name: 'English', code: 'en' }, { name: 'Afrikaans', code: 'af' }, { name: 'Zulu', code: 'zu' }, { name: 'Xhosa', code: 'xh' }] },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷', languages: [{ name: 'Korean', code: 'ko' }] },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', languages: [{ name: 'Spanish', code: 'es' }, { name: 'Catalan', code: 'ca' }, { name: 'Galician', code: 'gl' }, { name: 'Basque', code: 'eu' }] },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', languages: [{ name: 'Sinhala', code: 'si' }, { name: 'Tamil', code: 'ta' }] },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', languages: [{ name: 'Swedish', code: 'sv' }] },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', languages: [{ name: 'German', code: 'de' }, { name: 'French', code: 'fr' }, { name: 'Italian', code: 'it' }, { name: 'Romansh', code: 'rm' }] },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼', languages: [{ name: 'Chinese (Traditional)', code: 'zh-TW' }] },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', languages: [{ name: 'Thai', code: 'th' }] },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷', languages: [{ name: 'Turkish', code: 'tr' }] },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', languages: [{ name: 'Ukrainian', code: 'uk' }] },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', languages: [{ name: 'English', code: 'en' }] },
  { name: 'United States', code: 'US', flag: '🇺🇸', languages: [{ name: 'English', code: 'en' }, { name: 'Spanish', code: 'es' }] },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', languages: [{ name: 'Uzbek', code: 'uz' }] },
  { name: 'Vatican City', code: 'VA', flag: '🇻🇦', languages: [{ name: 'Latin', code: 'la' }, { name: 'Italian', code: 'it' }] },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪', languages: [{ name: 'Spanish', code: 'es' }] },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳', languages: [{ name: 'Vietnamese', code: 'vi' }] },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', languages: [{ name: 'Arabic', code: 'ar' }] },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', languages: [{ name: 'English', code: 'en' }, { name: 'Shona', code: 'sn' }, { name: 'Ndebele', code: 'nd' }] },
];

export const LANGUAGES = Array.from(new Map(COUNTRIES.flatMap(c => c.languages).map(l => [l.code, l])).values()).sort((a, b) => a.name.localeCompare(b.name));
